### ISSUE TITLE
Keycloak logout hook

### ISSUE THREAD

**Issue by ayian2004** [Acosix/alfresco-keycloak#19]
I want a user after successfully login in using the keycloak SSO service (implemented through this plugin), when logging out from Keycloak to also be logout from the Alfresco service. Hence I am looking if Alfresco-keycloak offers "logout hooks from Keycloak to get notified when a global logout takes place".

Thank you

**Comment by AFaust** [comment]
If you properly set the [admin URL in your Keycloak clients](https://github.com/Acosix/alfresco-keycloak/blob/master/repository/src/test/docker/test-realm.json#L19) then Keycloak will be able to call the backchannel logout hooks which are already part of the addon.

**Comment by ayian2004** [comment]
According to https://github.com/Acosix/alfresco-keycloak/blob/master/docs/Simple-Configuration.md the admi url of the alfresco client is set to /wcs/keycloak, which is not the same as the link you suggest.
The same applies for the alfresco share client, that is set to /page/keycloak, which is not the same as the link you suggest.

Do I need to include the full path, or leave it as is, i.e. relative?

**Comment by AFaust** [comment]
I coded a bit of "leniency" in the Keycloak admin hooks, i.e. via a pattern with [optional `/page/` prefix detection in Share](https://github.com/Acosix/alfresco-keycloak/blob/master/share/src/main/java/de/acosix/alfresco/keycloak/share/web/KeycloakAuthenticationFilter.java#L160) and [similar in Repository](https://github.com/Acosix/alfresco-keycloak/blob/master/repository/src/main/java/de/acosix/alfresco/keycloak/repo/authentication/KeycloakAuthenticationFilter.java#L109). So both the documentation and the links I provided are correct.

I don't know if it is just a formating issue in your last message, but the URL `https:///share` is definitely not correct. Keycloak has support for some relative URL resolution, but to be safe, you can always use the full path in the admin URL
