### ISSUE TITLE
Keycloak SSO Share startup logs

### ISSUE THREAD

**Issue by dharmendrapanday** [Acosix/alfresco-keycloak#37]
[share-config-custom.txt](https://github.com/Acosix/alfresco-keycloak/files/13346992/share-config-custom.txt)
[share-logs.txt](https://github.com/Acosix/alfresco-keycloak/files/13346782/share-logs.txt)
Hello,

I am trying to use Keycloak SSO with Alfresco Community Version Number: 7.2.1 (rd28d4873-blocal). I am using Docker.

The alfresco repo works fine but I get the following error message during the alfresco share startup.
Share starts well when I do not deploy (de.acosix.alfresco.keycloak.share-1.1.0-rc7.amp)amp modue, I tested this module without any share customization but I got the same error.

Attached share config and logs files.

14-Nov-2023 08:48:51.060 SEVERE [main] org.apache.catalina.core.StandardContext.startInternal Context [/share] startup failed due to previous errors
14-Nov-2023 08:48:51.088 SEVERE [main] org.apache.catalina.loader.WebappClassLoaderBase.checkThreadLocalMapForLeaks The web application [share] created a ThreadLocal withkey of type [org.springframework.extensions.webscripts.processor.FTLTemplateProcessor$NonBlockingObjectWrapper$1] (value [org.springframework.extensions.webscripts.processor.FTLTemplateProcessor$NonBlockingObjectWrapper$1@79c704f5]) and a value of type [freemarker.template.DefaultObjectWrapper] (value [freemarker.template.DefaultObjectWrapper@1235199412(2.3.0, useAdaptersForContainers=false, forceLegacyNonListCollections=true, iterableSupport=falseexposureLevel=1, exposeFields=false, preferIndexedReadMethod=true, treatDefaultMethodsAsBeanMembers=false, sharedClassIntrospCache=none, ...)]) but failed to remove it when the web application was stopped. Threads are going to be renewed over time to try and avoid a probable memory leak.

Regards
Dharmendra

**Comment by AFaust** [comment]
Did you find the cause of the problem and close the issue as a result, or did you give up because I wasn't able to react / reply sooner? If you found the cause of the problem, and it relates to a misconfiguration of the module, it would be good to know / document here, so that others may find it helpful if they run into the same issue.

**Comment by dharmendrapanday** [comment]
it was some configuration problems in keycloak server.
