### ISSUE TITLE
Upgrade Keycloak v24

### ISSUE THREAD

**Issue by dharmendrapanday** [Acosix/alfresco-keycloak#39]
We are running alfresco-keycloak  module with Alfresco Version 7.2 with Keycloak version v20 which works perfectly fine without any problem.

After Upgrade of Keycloak version v24 yesterday, We get the SSO login page where it redirect back to Alfresco login page after keycloak authentication again and again.
We have not enforced SSO login, Users(external users) have option login with basic auth and keycloak SSO( Company Employee) as well.

can you please suggest what could be wrong ....

**Comment by AFaust** [comment]
I have not checked what recent changes Keycloak v24 may have introduced that changed the behaviour. The most recent version I have used myself is v23, which worked fine. Do you have any log output or (anonymised) network trace that shows the behaviour?

**Comment by dharmendrapanday** [comment]
Sorry for reply late, Due to some other urgent work we put this on hold..

Now, I have started working again.
Here is error message I am getting in alfresco logs.

alfresco_1            | 2024-07-25 12:49:12,295  WARN  [content.transform.LocalTransformServiceRegistry] [QuartzScheduler_Worker-1] Transformer "htmlToPdfViaTXT" ignored as step transforms ("string", "libreoffice") do not exist. Read from resource alfresco/transforms/0100-basePipelines.json
share_1               |  2024-07-25 12:49:15,381  ERROR [keycloak.adapters.OAuthRequestAuthenticator] [http-nio-8080-exec-6] failed to turn code into token
share_1               |  2024-07-25 12:49:15,382  ERROR [keycloak.adapters.OAuthRequestAuthenticator] [http-nio-8080-exec-6] status from server: 400
share_1               |  2024-07-25 12:49:15,382  ERROR [keycloak.adapters.OAuthRequestAuthenticator] [http-nio-8080-exec-6]    {"error":"invalid_grant","error_description":"Incorrect redirect_uri"}
share_1               |  2024-07-25 12:49:15,382  WARN  [share.web.KeycloakAuthenticationFilter] [http-nio-8080-exec-6] Keycloak authentication failed due to <missing AuthenticationError details in request context>
proxy_1               | 10.6.75.186 - - [25/Jul/2024:12:49:15 +0000] "GET /share/page/?state=bdee52bc-6205-43b2-889d-d1eed3fb915f&session_state=9e7c6307-9869-4c9b-a617-f16338a2223d&iss=https%keycloal%2Fauth%2Frealms%2Fscania&code=a9e48317-c4c5-4e1d-bef4-d1ed078fb228.9e7c6307-9869-4c9b-a617-f16338a2223d.6602f579-bcba-4800-9db4-feb9f7f89a33 HTTP/1.1" 302 0 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36"
p

**Comment by dharmendrapanday** [comment]
There is an issue with Keycloak where user need to set "Exclude Issuer From Authentication Response"  to ON.
Here is the article.
https://github.com/keycloak/keycloak/discussions/25684
