### ISSUE TITLE
A question

### ISSUE THREAD

**Issue by MarkoArsic** [Acosix/alfresco-keycloak#4]
Hello,
in Keycloak, we have a certain groups with roles assigned to the groups.
Will Alfresco be able to know wihich content to serve or not, based on Keycloak groups with roles assigned to the groups.
So, content authorization based on keycloak groups in Alfresco is the main issue.
Thank you!

**Comment by AFaust** [comment]
With the module in place, you can assign permissions on content to those defined roles, and when a user is authenticated via Keycloak, those roles are available for ACL evaluation. In short: Yes, Alfresco will be able to know which content to server in this case.

**Comment by MarkoArsic** [comment]
Thank you very much!
