### ISSUE TITLE
How to go from share to identity provider directly?

### ISSUE THREAD

**Issue by zkoria** [Acosix/alfresco-keycloak#8]
Hi @AFaust

currently, the flow I have is the following:

![imagen](https://user-images.githubusercontent.com/39277137/116909019-36435e80-ac09-11eb-9c29-ec35d623689d.png)

click on "Login via SSO":

![imagen](https://user-images.githubusercontent.com/39277137/116909138-62f77600-ac09-11eb-8a5e-56c5d6e5e11a.png)

click on Azure AD:

![imagen](https://user-images.githubusercontent.com/39277137/116909196-7c98bd80-ac09-11eb-919c-03eae0e37b46.png)

How can I skip the keycloak view step and go directly to the third view from "Login via SSO? 

thanks in advance, regards.

**Comment by AFaust** [comment]
You have to set the Azure AD provider as the default provider in Keycloak - see https://www.keycloak.org/docs/latest/server_admin/index.html#default_identity_provider

**Comment by zkoria** [comment]
Thanks for the reply @AFaust, how you suggested it was solved as follows:

 
![imagen](https://user-images.githubusercontent.com/39277137/118037743-dc8f1280-b333-11eb-9037-d1c6b6de9dfe.png)


![imagen](https://user-images.githubusercontent.com/39277137/118037803-f0d30f80-b333-11eb-88be-7141de52d8cf.png)

![imagen](https://user-images.githubusercontent.com/39277137/118037822-f7fa1d80-b333-11eb-9d4d-4493c1530ed9.png)

**Comment by AFaust** [comment]
Ok - I'll close this issue then...
