### ISSUE TITLE
Requesting to re-authenticate with Keycloak

### ISSUE THREAD

**Issue by ayian2004** [Acosix/alfresco-keycloak#9]
Dear @AFaust 
I have successfully (???) installed and configured your Alfresco-Keycloak add-on in order to support integration with Keycloak Identity service. 

However, I have the following situation: We have implemented a web-desktop application (https://qlack.com/webdesktop), that simulates a virtual desktop environment in one single browser window and allows multiple web applications to be integrated under the same environment. The web-desktop application is integrated with Keycloak/SSO in order to handle the authentication and authorization steps for the integrated applications.

After successfully logging in to our web-desktop application the user is presented with a list of applications, one of them being the Alfresco application. However, the user is prompted to re-enter his/hers SSO credentials. 

![image](https://user-images.githubusercontent.com/1390684/117291345-8cb5d480-ae77-11eb-8eca-e32c527340d2.png)

Is there a way/configuration that would allow the Alfresco Share application to be accessed without the user having to re-enter his/hers credentials, since he/she are already authenticated? So what I want is to skip the above screen, since the user is already authenticated and simply navigate to this screen.
![image](https://user-images.githubusercontent.com/1390684/117291561-d43c6080-ae77-11eb-87c7-d2bc101b0e70.png)

Thank you

**Comment by AFaust** [comment]
From the screenshot of the Share login form I doubt that the Keycloak module is configured correctly - it may be installed, but the login screen does not include the expected extra login button to use Keycloak for authentication. Please check the [WIP documentation - simple configuration](https://github.com/Acosix/alfresco-keycloak/blob/docs-wip/docs/Simple-Configuration.md) for a reference to the latest release candidate version. There you will also find the necessary configuration (`force-keycloak-sso`) to have Share force a redirect to Keycloak to avoid the separate login when the user is already authenticated there.

**Comment by ayian2004** [comment]
Hi @AFaust 
I have "followed" the instructions and the following was done:
1. Enabled the Token Exchange Feature by creating in my Keycloak docker instance the following file /opt/jboss/keycloak/standalone/configuration/profile.properties with a single entry: feature.token_exchange=enabled
2. Created new realm, named alfresco and inside two clients for Repository and Share (
[Alfresco-Keycloak-Clients.zip](https://github.com/Acosix/alfresco-keycloak/files/6440918/Alfresco-Keycloak-Clients.zip)
). However, I cannot define an authorisation policy on the pre-existing client realm-management, as I cannot find an "Authorization" tab. see below:
![image](https://user-images.githubusercontent.com/1390684/117428811-11175e80-af2f-11eb-965b-5a636381800c.png)
3. Enabled the Keycloak authentication subsystem in the alfresco-global.properties (
[alfresco-global.zip](https://github.com/Acosix/alfresco-keycloak/files/6440961/alfresco-global.zip)
)
4. Updated the <tomcat>/shared/classes/alfresco/web-extension/share-config-custom.xml with <config evaluator="string-compare" condition="Keycloak">
        <keycloak-auth-config>
            <enhance-login-form>true</enhance-login-form>
            <enable-sso-filter>true</enable-sso-filter>
            <force-keycloak-sso>false</force-keycloak-sso>
            <perform-token-exchange>true</perform-token-exchange>
        </keycloak-auth-config>
        <keycloak-adapter-config>
            <directAuthHost></directAuthHost>
            <auth-server-url>https://foresight.eurodyn.com/auth</auth-server-url>
            <always-refresh-token>true</always-refresh-token>
            <connection-pool-size>123</connection-pool-size>
            <realm>alfresco</realm>
            <resource>Alfresco-Share</resource>
            <ssl-required>none</ssl-required>
            <public-client>false</public-client>
            <credentials>
                <provider>secret</provider>
                <secret>xxxxxxxxxxxx</secret>
            </credentials>
        </keycloak-adapter-config>
    </config>

<config evaluator="string-compare" condition="Remote">
        <remote>
            <connector>
                <id>alfrescoCookie</id>
                <name>Alfresco Connector</name>
                <description>Connects to an Alfresco instance using cookie-based authentication and awareness of Keycloak access tokens</description>
                <class>de.acosix.alfresco.keycloak.share.remote.AccessTokenAwareSlingshotAlfrescoConnector</class>
            </connector>

            <endpoint>
                <id>alfresco</id>
                <name>Alfresco - user access</name>
                <description>Access to Alfresco Repository WebScripts that require user authentication</description>
                <connector-id>alfrescoCookie</connector-id>
                <endpoint-url>https://foresight.eurodyn.com/alfresco/wcs</endpoint-url>
                <identity>user</identity>
                <external-auth>true</external-auth>
            </endpoint>

            <endpoint>
                <id>alfresco-feed</id>
                <name>Alfresco Feed</name>
                <description>Alfresco Feed - supports basic HTTP authentication via the EndPointProxyServlet</description>
                <connector-id>alfrescoCookie</connector-id>
                <endpoint-url>https://foresight.eurodyn.com/alfresco/wcs</endpoint-url>
                <basic-auth>true</basic-auth>
                <identity>user</identity>
                <external-auth>true</external-auth>
            </endpoint>

            <endpoint>
                <id>alfresco-api</id>
                <parent-id>alfresco</parent-id>
                <name>Alfresco Public API - user access</name>
                <description>Access to Alfresco Repository Public API that require user authentication. This makes use of the authentication
                    that is provided by parent 'alfresco' endpoint.
                </description>
                <connector-id>alfrescoCookie</connector-id>
                <endpoint-url>https://foresight.eurodyn.com/alfresco/api</endpoint-url>
                <identity>user</identity>
                <external-auth>true</external-auth>
            </endpoint>
        </remote>
    </config>

5. I have restarted all involved containers.... and now I can see the missing "Login via SSO" button

However, when I click I get an invalid redirect uri as you can see:
https://foresight.eurodyn.com/auth/realms/alfresco/protocol/openid-connect/auth?response_type=code&client_id=Alfresco-Share&redirect_uri=http%3A%2F%2Fforesight-server.eurodyn.com%3A8080%2Fshare%2Fpage&state=0561f0c6-a6f8-4a7e-8e35-864c012b137c&login=true&scope=openid

for some reason the redirect_uri as you can see is set to: http://foresight-server.eurodyn.com:8080/share/page

What am I doing now wrong?

Thanks for the help

**Comment by AFaust** [comment]
Note:

- direct auth host is not necessary to be specified if the protocol + host + port is exactly the same as in the auth server URL - it is only necessary when there is some form of NAT / DNS mapping involved
- the incorrect Share redirect looks to me like the result of an incorrect / incomplete proxy setup - unfortunately, quite a few examples you find on this on the net are incomplete, often lacking in handling the [X-Forwarded-Proto](https://github.com/Acosix/acosix-docker-generic/blob/master/baseimage-apache/src/main/resources/alfresco-universal.host.ssl.conf.sample#L19) or X-Forwarded-Port headers, and not setting a [proxy port in Tomcat](https://github.com/Acosix/acosix-docker-generic/blob/master/baseimage-tomcat8/src/main/resources/server.xml#L18)
- What version of Keycloak are you using and are you a full administrator? Your Client config for realm-management is missing quite a few elements I would expect to be there. See the following for reference from a relatively current Keycloak install (11.x)

![grafik](https://user-images.githubusercontent.com/2211521/117441776-2e9bf680-af36-11eb-9e43-e284d96ddb11.png)

**Comment by ayian2004** [comment]
Hi @AFaust 

- I have removed the <directAuthHost>
- Regarding the VM hosting Alfresco it is not publicly exposed. Instead I use a reverse proxy (nginx) on a machine that is exposed and it includes the following entries [app.zip](https://github.com/Acosix/alfresco-keycloak/files/6441156/app.zip)
- I am using Keycloak jboss/keycloak:11.0.3 and I am full admin
- Regarding the realm-management client what I've shown was  the default from Keycloak when I created the new Alfresco realm. Is it possible to send me an exported realm-management client?

**Comment by AFaust** [comment]
The project already contains minimal realm exports, e.g. [as part of Share's Docker setup](https://github.com/Acosix/alfresco-keycloak/blob/master/share/src/test/docker/test-realm.json)

**Comment by ayian2004** [comment]
Hi @AFaust 
I have updated the realm-management client and created 2 new clients namely, alfresco and alfresco-share as per your instructions. However, I cannot create the realm-management client with Access Type set to "bearer-only", as this will disable all other configuration tabs, namely "Authorization" and "Service Account Roles" that are needed in order to configure the authorisation policy, as indicated in your [instructions](https://github.com/Acosix/alfresco-keycloak/blob/master/docs/Simple-Configuration.md). Am I doing something wrong?

**Comment by AFaust** [comment]
By choosing "bearer-only" you are removing / disabling the ability for Keycloak to authenticate the client, so it cannot have a "service account role" for that client because the client cannot login with that role. Subsequently, without a secure authentication, authorisation also goes out of the window, along with any functionalities that are based on that - either Keycloak-internally or for other clients.
It would technically still be possible to have an integration without token exchange by using the same client for both Repository and Share, and disabling token exchange via the share-config-custom.xml config for the module. I generally don't test that as much as I consider it to be a hacky / incomplete integration - in fact it is how Alfresco's own Identity Management Service integration works, which is the only reason I included that option for a bit easier switch from AIMS to my module.

**Comment by ayian2004** [comment]
Regarding the the incorrect Share you suggested an incorrect / incomplete proxy setup on alfresco-share server.xml file. However, I am confused as what is the proper connector attributes. 
My alfresco community docker installation, runs on VM1 and includes a nginx proxy (docker name: docker-compose_proxy_1). This VM is not publicly exposed. My overall project installation runs on VM2 and includes another nginx proxy (docker name: qlack-webdesktop-nginx). This VM is publicly exposed and I want all accesses/redirects to be handled from there.
Can you please

**Comment by AFaust** [comment]
This error is due to the fact that you probably have a self-signed server certificate for SSL or are using a CA that is not in the default trusted CA set of the JVM. You have various options to deal with this:

- use directAuthHost configuration to have Share / ACS go directly to the Keycloak host via HTTP without going through the proxy (via auth-server-url)
- ensure the CA for your server certificate is added to the cacerts trust store or use a custom truststore via the relevant JVM -D flag(s)
- configure the Keycloak adapter with a custom truststore (potentially preferable to the global JVM truststore as it reduces chance of unforseen side effects) by configuring the `truststore` (path) and `truststore-password` properties (in the same way / place as the `auth-server-url` one)

**Comment by ayian2004** [comment]
Thank you @AFaust together with the comments from #12 I've managed to successfully authenticate via SSO/Keycloak.
